更新 SSP
支持VMess协议(ws,ws+tls,tcp,tcp+tls)
支持从U盘SSP目录下启动可执行文件(trojan,v2ray,v2ray-plugin)
修复某些节点失效造成连接数过多的问题(nf_conntrack: table full)
修复特定条件下透明代理开启失败的问题(任务失败!错误代码:1)
更新透明代理自动分流规则
删除地址集合自动配置功能
以及其它一些小的修复和调整

diff --git a/trunk/user/shadowsocks/scripts/ss-rules b/trunk/user/shadowsocks/scripts/ss-rules
--- a/trunk/user/shadowsocks/scripts/ss-rules
+++ b/trunk/user/shadowsocks/scripts/ss-rules
@@ -9,30 +9,26 @@ private_addr="0.0.0.0/8          10.0.0.0/8         100.64.0.0/10      127.0.0.0
               224.0.0.0/4        240.0.0.0/4        255.255.255.255/32"
 
 iptn="iptables -t nat"
-iptm="iptables -t mangle"
 iptf="iptables -t filter"
-amtf="/tmp/SSP_AUTOM"
+iptm="iptables -t mangle"
+ipt_n="/tmp/ss-rules_iptables_nat"
+ipt_f="/tmp/ss-rules_iptables_filter"
+ipt_m="/tmp/ss-rules_iptables_mangle"
+
+routemark="0x64"
+ruletable="100"
 
 flush_rules()
 {
 echo -1000 > /proc/$$/oom_score_adj
-nochain=0
-if [ "$1" = "2" ]; then
-  iptables-save -c | grep -v -E "SSP_OUTPUT|SSP_PREROUTING|SSP_RULES|SSP_INPUT|TPROXY" | iptables-restore -c
-  $iptn -F SSP_AGENT || nochain=$(echo "$?")
-  $iptm -F SSP_AGENT
-  $iptm -X SSP_AGENT
-else
-  iptables-save -c | grep -v -E "SSP_|TPROXY" | iptables-restore -c
-fi
+iptables-save -c | grep -v -E "SSP_|TPROXY" | iptables-restore -c
 ipset destroy servers
 ipset destroy private
 ipset destroy gfwlist
 ipset destroy chnlist
-ip route del local 0.0.0.0/0 dev lo table 100
-ip rule del fwmark 0x64 lookup 100
+ip route del local default dev lo table $ruletable
+ip rule del fwmark $routemark table $ruletable
 ip route flush cache
-rm -rf $amtf
 return 0
 }
 
@@ -50,59 +46,56 @@ ipset -! restore <<-EOF || return 1
   $(cat ${chn_list:=/dev/null} 2>/dev/null | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}" | sed -e "s/^/add chnlist /")
   $(cat ${chnexp_list:=/dev/null} 2>/dev/null | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}" | sed -e "s/^/add chnlist /")
 EOF
-return 0
 }
 
 ipt_nat()
 {
-echo "*nat" > $amtf
-if [ "$agent_mode" == "0" ] || [ "$agent_mode" == "1" ] || [ "$nochain" = "1" ]; then
-  echo ":SSP_AGENT - [0:0]" >> $amtf
-fi
-[ "$nochain" = "1" ] && echo ":SSP_AUTOM - [0:0]" >> $amtf
-echo ":SSP_OUTPUT - [0:0]" >> $amtf
-echo ":SSP_PREROUTING - [0:0]" >> $amtf
-echo ":SSP_RULES - [0:0]" >> $amtf
-[ "$nochain" = "1" ] && for CIDR_08 in $(seq 1 223); do
-  [ "$CIDR_08" = "10" ] || [ "$CIDR_08" = "127" ] || for CIDR_16 in $(seq 0 255); do
-    echo "-A SSP_AUTOM -d $CIDR_08.$CIDR_16.0.0/16 -m limit --limit 3/sec --limit-burst 3 -j SSP_AGENT" >> $amtf
-  done
-done
-echo "COMMIT" >> $amtf && iptables-restore --noflush < $amtf && rm -rf $amtf || return 1
-$iptn -A SSP_PREROUTING -m set --match-set servers dst -j RETURN
-[ "$server_addr" != "0" ] && $iptn -A SSP_PREROUTING -d $server_addr -j RETURN
-$iptn -A SSP_PREROUTING -p tcp -j SSP_RULES
-$iptn -A SSP_OUTPUT -m set --match-set servers dst -j RETURN
-[ "$server_addr" != "0" ] && $iptn -A SSP_OUTPUT -d $server_addr -j RETURN
-$iptn -A SSP_OUTPUT -p tcp -j SSP_RULES
-$iptn -A SSP_RULES -m state --state RELATED,ESTABLISHED -j RETURN
-$iptn -A SSP_RULES -m set --match-set private dst -j RETURN
-[ "$agent_mode" == "0" ] && $iptn -A SSP_RULES -j SSP_AGENT
-[ "$agent_mode" == "1" ] && $iptn -A SSP_RULES -m set --match-set chnlist dst -j RETURN
-[ "$agent_mode" != "0" ] && $iptn -A SSP_RULES -m set --match-set gfwlist dst -j SSP_AGENT
-[ "$agent_mode" == "2" ] && $iptn -A SSP_RULES -m set --match-set chnlist dst -j RETURN
-[ "$agent_mode" == "2" ] && $iptn -A SSP_RULES -j LOG --log-prefix "ipnotset "
-[ "$agent_mode" == "2" ] && $iptn -A SSP_RULES -j SSP_AUTOM
-[ "$agent_mode" == "1" ] && $iptn -A SSP_RULES -j SSP_AGENT
-[ "$agent_mode" == "2" ] && $iptn -A SSP_RULES -j RETURN
-$iptn -A SSP_AGENT -p tcp -j REDIRECT --to-ports $local_port
-$iptn -I OUTPUT 1 -j SSP_OUTPUT
-$iptn -I PREROUTING 1 -j SSP_PREROUTING
-return 0
+echo "*nat" > $ipt_n
+echo ":SSP_AGENT - [0:0]" >> $ipt_n
+[ "$agent_mode" != "0" ] && echo ":SSP_AUTOC - [0:0]" >> $ipt_n
+[ "$agent_mode" != "0" ] && echo ":SSP_AUTOG - [0:0]" >> $ipt_n
+[ "$agent_mode" != "0" ] && echo ":SSP_AUTOM - [0:0]" >> $ipt_n
+echo ":SSP_OUTPUT - [0:0]" >> $ipt_n
+echo ":SSP_PREROUTING - [0:0]" >> $ipt_n
+echo ":SSP_RULES - [0:0]" >> $ipt_n
+echo "-A PREROUTING -j SSP_PREROUTING" >> $ipt_n
+echo "-A OUTPUT -j SSP_OUTPUT" >> $ipt_n
+echo "-A SSP_AGENT -p tcp -m connlimit --connlimit-upto 256 --connlimit-mask 32 --connlimit-saddr -j REDIRECT --to-ports $local_port" >> $ipt_n
+[ "$agent_mode" != "0" ] && echo "-A SSP_AUTOC -p tcp -m connlimit --connlimit-upto 256 --connlimit-mask 32 --connlimit-saddr -m connlimit --connlimit-above $DR2 --connlimit-mask 32 --connlimit-daddr -j SSP_AGENT" >> $ipt_n
+[ "$agent_mode" != "0" ] && echo "-A SSP_AUTOC -p tcp -m connlimit --connlimit-upto 256 --connlimit-mask 32 --connlimit-saddr -m connlimit --connlimit-upto $DR2 --connlimit-mask 32 --connlimit-daddr -j RETURN" >> $ipt_n
+[ "$agent_mode" != "0" ] && echo "-A SSP_AUTOG -p tcp -m connlimit --connlimit-upto 256 --connlimit-mask 32 --connlimit-saddr -m connlimit --connlimit-above $DR2 --connlimit-mask 32 --connlimit-daddr -j RETURN" >> $ipt_n
+[ "$agent_mode" != "0" ] && echo "-A SSP_AUTOG -p tcp -m connlimit --connlimit-upto 256 --connlimit-mask 32 --connlimit-saddr -m connlimit --connlimit-upto $DR2 --connlimit-mask 32 --connlimit-daddr -j SSP_AGENT" >> $ipt_n
+[ "$agent_mode" == "1" ] && echo "-A SSP_AUTOM -p tcp -m connlimit --connlimit-upto 256 --connlimit-mask 32 --connlimit-saddr -m connlimit --connlimit-above $DR1 --connlimit-mask 32 --connlimit-daddr -j RETURN" >> $ipt_n
+[ "$agent_mode" == "1" ] && echo "-A SSP_AUTOM -p tcp -m connlimit --connlimit-upto 256 --connlimit-mask 32 --connlimit-saddr -m connlimit --connlimit-upto $DR1 --connlimit-mask 32 --connlimit-daddr -j SSP_AGENT" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_AUTOM -p tcp -m connlimit --connlimit-upto 256 --connlimit-mask 32 --connlimit-saddr -m connlimit --connlimit-above $DR1 --connlimit-mask 32 --connlimit-daddr -j SSP_AGENT" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_AUTOM -p tcp -m connlimit --connlimit-upto 256 --connlimit-mask 32 --connlimit-saddr -m connlimit --connlimit-upto $DR1 --connlimit-mask 32 --connlimit-daddr -j RETURN" >> $ipt_n
+echo "-A SSP_OUTPUT -p tcp -j SSP_RULES" >> $ipt_n
+echo "-A SSP_PREROUTING -p tcp -j SSP_RULES" >> $ipt_n
+echo "-A SSP_RULES -m state --state RELATED,ESTABLISHED -j RETURN" >> $ipt_n
+echo "-A SSP_RULES -m set --match-set private dst -j RETURN" >> $ipt_n
+echo "-A SSP_RULES -m set --match-set servers dst -j RETURN" >> $ipt_n
+[ "$server_addr" = "0" ] || echo "-A SSP_RULES -d $server_addr -j RETURN" >> $ipt_n
+[ "$agent_mode" == "0" ] && echo "-A SSP_RULES -j SSP_AGENT" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_RULES -m set --match-set gfwlist dst -j SSP_AUTOG" >> $ipt_n
+[ "$agent_mode" != "0" ] && echo "-A SSP_RULES -m set --match-set chnlist dst -j SSP_AUTOC" >> $ipt_n
+[ "$agent_mode" == "1" ] && echo "-A SSP_RULES -m set --match-set gfwlist dst -j SSP_AUTOG" >> $ipt_n
+[ "$agent_mode" != "0" ] && echo "-A SSP_RULES -j SSP_AUTOM" >> $ipt_n
+echo "COMMIT" >> $ipt_n && iptables-restore --noflush < $ipt_n && rm -rf $ipt_n || return 1
 }
 
 ipt_filter()
 {
-$iptf -N SSP_INPUT
-$iptf -A SSP_INPUT -m set --match-set private src -j RETURN
-$iptf -A SSP_INPUT -p tcp -m set --match-set servers src -m tcp --tcp-flags RST RST -m state --state RELATED,ESTABLISHED -m limit --limit 1/min --limit-burst 1 -j RETURN
-$iptf -A SSP_INPUT -p tcp -m set --match-set servers src -m tcp --tcp-flags RST RST -j DROP
-[ "$server_addr" != "0" ] && $iptf -A SSP_INPUT -s $server_addr -p tcp -m tcp --tcp-flags RST RST -m state --state RELATED,ESTABLISHED -m limit --limit 1/min --limit-burst 1 -j RETURN
-[ "$server_addr" != "0" ] && $iptf -A SSP_INPUT -s $server_addr -p tcp -m tcp --tcp-flags RST RST -j DROP
-$iptf -A SSP_INPUT -p tcp -m tcp --tcp-flags RST RST -m state --state INVALID,NEW -j DROP
-$iptf -A SSP_INPUT -j RETURN
-$iptf -I INPUT 1 -j SSP_INPUT
-return 0
+echo "*filter" > $ipt_f
+echo ":SSP_INPUT - [0:0]" >> $ipt_f
+echo "-A INPUT -j SSP_INPUT" >> $ipt_f
+echo "-A SSP_INPUT -m set --match-set private src -j RETURN" >> $ipt_f
+echo "-A SSP_INPUT -p tcp -m set --match-set servers src -m tcp --tcp-flags RST RST -m state --state RELATED,ESTABLISHED -m limit --limit 1/min --limit-burst 1 -j RETURN" >> $ipt_f
+echo "-A SSP_INPUT -p tcp -m set --match-set servers src -m tcp --tcp-flags RST RST -j DROP" >> $ipt_f
+[ "$server_addr" = "0" ] || echo "-A SSP_INPUT -s $server_addr -p tcp -m tcp --tcp-flags RST RST -m state --state RELATED,ESTABLISHED -m limit --limit 1/min --limit-burst 1 -j RETURN" >> $ipt_f
+[ "$server_addr" = "0" ] || echo "-A SSP_INPUT -s $server_addr -p tcp -m tcp --tcp-flags RST RST -j DROP" >> $ipt_f
+echo "-A SSP_INPUT -p tcp -m tcp --tcp-flags RST RST -m state --state INVALID,NEW -j DROP" >> $ipt_f
+echo "-A SSP_INPUT -j RETURN" >> $ipt_f
+echo "COMMIT" >> $ipt_f && iptables-restore --noflush < $ipt_f && rm -rf $ipt_f || return 1
 }
 
 ipt_mangle()
@@ -110,32 +103,30 @@ ipt_mangle()
 if !(lsmod | grep -q xt_TPROXY ); then
   modprobe xt_TPROXY
 fi
-ip rule add fwmark 0x64 lookup 100
-ip route add local 0.0.0.0/0 dev lo table 100
-$iptm -N SSP_PREROUTING
-$iptm -N SSP_OUTPUT
-$iptm -N SSP_RULES
+ip route add local default dev lo table $ruletable
+ip rule add fwmark $routemark table $ruletable
 $iptm -N SSP_AGENT
-$iptm -A SSP_PREROUTING -m set --match-set servers dst -j RETURN
-[ "$server_addr" != "0" ] && $iptm -A SSP_PREROUTING -d $server_addr -j RETURN
-$iptm -A SSP_PREROUTING -p udp -j SSP_RULES
-$iptm -A SSP_OUTPUT -m set --match-set servers dst -j RETURN
-[ "$server_addr" != "0" ] && $iptm -A SSP_OUTPUT -d $server_addr -j RETURN
+$iptm -N SSP_OUTPUT
+$iptm -N SSP_PREROUTING
+$iptm -N SSP_RULES
+$iptm -I PREROUTING 1 -j SSP_PREROUTING
+$iptm -I OUTPUT 1 -j SSP_OUTPUT
+$iptm -A SSP_AGENT -j CONNMARK --restore-mark
+$iptm -A SSP_AGENT -j CONNMARK --set-mark $routemark
+$iptm -A SSP_AGENT -j CONNMARK --save-mark
 $iptm -A SSP_OUTPUT -p udp -j SSP_RULES
-$iptm -A SSP_RULES -m mark --mark 0x64/0x64 -j RETURN
+$iptm -A SSP_PREROUTING -p udp -m mark --mark $routemark -j TPROXY --on-port $local_port
+$iptm -A SSP_PREROUTING -p udp -j SSP_RULES
+$iptm -A SSP_RULES -m mark --mark $routemark -j RETURN
 $iptm -A SSP_RULES -m set --match-set private dst -j RETURN
+$iptm -A SSP_RULES -m set --match-set servers dst -j RETURN
+[ "$server_addr" = "0" ] || $iptm -A SSP_RULES -d $server_addr -j RETURN
 [ "$agent_mode" == "0" ] && $iptm -A SSP_RULES -j SSP_AGENT
-[ "$agent_mode" == "1" ] && $iptm -A SSP_RULES -m set --match-set chnlist dst -j RETURN
-[ "$agent_mode" != "0" ] && $iptm -A SSP_RULES -m set --match-set gfwlist dst -j SSP_AGENT
-[ "$agent_mode" == "2" ] && $iptm -A SSP_RULES -m set --match-set chnlist dst -j RETURN
-[ "$agent_mode" == "2" ] && $iptm -A SSP_RULES -j LOG --log-prefix "ipnotset "
+[ "$agent_mode" == "2" ] && $iptm -A SSP_RULES -m set --match-set gfwlist dst -j SSP_AGENT
+[ "$agent_mode" != "0" ] && $iptm -A SSP_RULES -m set --match-set chnlist dst -j RETURN
+[ "$agent_mode" == "1" ] && $iptm -A SSP_RULES -m set --match-set gfwlist dst -j SSP_AGENT
 [ "$agent_mode" == "1" ] && $iptm -A SSP_RULES -j SSP_AGENT
 [ "$agent_mode" == "2" ] && $iptm -A SSP_RULES -j RETURN
-$iptm -A SSP_AGENT -p udp -m conntrack --ctstate NEW -j CONNMARK --set-mark 0x64/0x64
-$iptm -A SSP_AGENT -p udp -m conntrack --ctstate NEW -j CONNMARK --restore-mark
-$iptm -I OUTPUT 1 -j SSP_OUTPUT
-$iptm -I PREROUTING 1 -j SSP_PREROUTING
-$iptm -I PREROUTING 2 -p udp -m mark --mark 0x64/0x64 -j TPROXY --on-port $local_port
 return 0
 }
 
@@ -143,19 +134,20 @@ usage()
 {
 cat <<-EOF
 
-  ss-rules [选项] [赋值]         [说明]
-           -s     <server_addr>  服务器地址      支持域名和IP/CIDR格式 赋值[0]禁用
-           -i     <local_port>   本地端口        
-           -g     <gfw_list>     黑名单地址列表  IP/CIDR格式
-           -c     <chn_list>     国内路由表      IP/CIDR格式
-           -e     <chnexp_list>  白名单地址列表  IP/CIDR格式
-           -b     <black_ip>     黑名单地址      多个IP/CIDR使用[,]隔开
-           -w     <white_ip>     白名单地址      多个IP/CIDR使用[,]隔开
-           -a     <agent_mode>   透明代理模式    全局代理[0] 国内路由表[1] 黑名单域名[2]
-           -t                    透明代理协议    TCP[REDIRECT]
-           -m                    透明代理协议    TCP[REDIRECT] UDP[TPROXY]
-           -f                    清除规则        
-           -h                    显示帮助        
+  ss-rules [选项] [赋值]            [说明]
+           -s     <server_addr>     服务器地址      支持域名和IP/CIDR格式 赋值[0]禁用
+           -i     <local_port>      本地端口        
+           -g     <gfw_list>        黑名单地址列表  IP/CIDR格式
+           -c     <chn_list>        国内路由表      IP/CIDR格式
+           -e     <chnexp_list>     白名单地址列表  IP/CIDR格式
+           -b     <black_ip>        黑名单地址      多个IP/CIDR使用[,]隔开
+           -w     <white_ip>        白名单地址      多个IP/CIDR使用[,]隔开
+           -a     <agent_mode>      透明代理模式    全局代理[0] 国内路由表[1] 黑名单域名[2]
+                  <diversion_rate>  自动分流        灵敏[1] 准确[2]
+           -t                       透明代理协议    TCP[REDIRECT]
+           -m                       透明代理协议    TCP[REDIRECT] UDP[TPROXY]
+           -f                       清除规则        
+           -h                       显示帮助        
 
 EOF
 exit $1
@@ -194,13 +186,17 @@ while getopts ":s:i:g:c:e:b:w:a:tmfh" arg; do
       ;;
     a)
       [ -z "$OPTARG" ] && usage 9
-      agent_mode="$OPTARG"
+      agentmode_diversionrate="$OPTARG"
+      agent_mode=${agentmode_diversionrate:0:1}
+      diversion_rate=${agentmode_diversionrate:1:1}
+      DR1="$diversion_rate"
+      DR2=$(expr $DR1 \* 4)
       ;;
     t)
-      flush_rules $agent_mode 2>/dev/null && gen_ipset && ipt_nat && ipt_filter
+      flush_rules 2>/dev/null && gen_ipset && ipt_nat && ipt_filter
       ;;
     m)
-      flush_rules $agent_mode 2>/dev/null && gen_ipset && ipt_nat && ipt_filter && ipt_mangle
+      flush_rules 2>/dev/null && gen_ipset && ipt_nat && ipt_filter && ipt_mangle
       ;;
     f)
       flush_rules 2>/dev/null
